name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        runtimes: ['python3.7', 'python3.8']
        gdal-version: [2.4, 3.1, 3.2]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install docker boto3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build layers
        if: "!contains(github.ref, 'tags')"
        run: python scripts/deploy.py ${{ matrix.gdal-version }} ${{ matrix.runtimes }} geo

      - name: Build and Deploy layers
        if: contains(github.ref, 'tags')
        run: python scripts/deploy.py ${{ matrix.gdal-version }} ${{ matrix.runtimes }} geo --deploy
